<a href="https://colab.research.google.com/github/ConfusedKlutz/Cloud_Computing_LAB/blob/main/LAB2(102216039_UCS531_24_25).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
import pandas as pd

# Define the size of the matrix
rows, cols = 50, 50

# Generate random integers between 0 and 100
data = np.random.randint(0, 101, size=(rows, cols))
print (data)
# Save to CSV
df = pd.DataFrame(data)
df.to_csv('large_random_matrix.csv', index=False, header=False)

print("Data file created successfully!")

#to assign subsequent rows of the matrix to the first row's elements





[[19 55 17 ... 77 95 77]
 [ 0  5 23 ... 77 25 94]
 [38 55 69 ... 96 43 69]
 ...
 [65 52 94 ... 14 24 88]
 [46 26  5 ... 32 71 80]
 [72 28 93 ... 53 12 14]]
Data file created successfully!


In [36]:
import numpy as np

# Define the size of the matrix
rows, cols = 5, 5  # You can change the size as needed

# Generate random integers between 0 and 100
data = np.random.randint(0, 101, size=(rows, cols))

print("Original Matrix:")
print(data)

# Flatten all subsequent rows and assign them to the first row
flattened_rows = data[1:].flatten()
print("\nFlattened subsequent rows:")
print(flattened_rows)

# First row
a = data[0]
print("\nFirst row:")
print(a)
print(f"Length of first row: {len(a)}")

# Create dictionary
d = dict()

# Check if we have more elements in flattened rows than in the first row
min_len = min(len(a), len(flattened_rows))

for i in range(min_len):
    d[a[i]] = flattened_rows[i]

print("\nDictionary of first row elements as keys and subsequent row elements as values:")
print(d)


Original Matrix:
[[ 4  9 91 13 40]
 [ 0 80  9 99 26]
 [ 0 77 46 44 53]
 [ 1 26 20 67 42]
 [46 71 45 74 38]]

Flattened subsequent rows:
[ 0 80  9 99 26  0 77 46 44 53  1 26 20 67 42 46 71 45 74 38]

First row:
[ 4  9 91 13 40]
Length of first row: 5

Dictionary of first row elements as keys and subsequent row elements as values:
{4: 0, 9: 80, 91: 9, 13: 99, 40: 26}


In [37]:
import numpy as np

# Define the size of the matrix
rows, cols = 50,50  # You can change the size as needed

# Generate random integers between 0 and 100
data = np.random.randint(0, 101, size=(rows, cols))

print("Original Matrix:")
print(data)

# Create dictionary to hold lists of subsequent row elements for each first row element
d = dict()

for i in range(cols):
    # Collect all elements from column i in the subsequent rows
    column_elements = data[1:, i].tolist()
    print(column_elements)
    d[data[0, i]] = column_elements

print("\nDictionary of first row elements as keys and lists of subsequent row elements as values:")
print(d)


Original Matrix:
[[  1  23  84 ...  93   4  19]
 [ 95  37  46 ...  63  77  15]
 [ 91   9   3 ...  76  52  14]
 ...
 [ 73  80 100 ...  55  67  81]
 [ 71   2  52 ...  82  35  39]
 [ 56  36  80 ...  47  61   1]]
[95, 91, 41, 91, 26, 59, 13, 98, 46, 7, 60, 1, 85, 16, 24, 26, 55, 79, 42, 80, 42, 43, 43, 38, 52, 27, 19, 23, 12, 66, 56, 47, 26, 72, 48, 94, 34, 55, 56, 95, 22, 21, 71, 21, 39, 4, 73, 71, 56]
[37, 9, 77, 94, 66, 83, 68, 96, 69, 39, 58, 60, 67, 51, 38, 16, 36, 99, 69, 82, 22, 30, 66, 54, 90, 54, 56, 96, 55, 14, 95, 48, 27, 72, 80, 96, 29, 96, 99, 46, 1, 1, 1, 60, 6, 98, 80, 2, 36]
[46, 3, 17, 17, 41, 10, 78, 58, 48, 74, 74, 40, 78, 63, 38, 31, 41, 62, 3, 77, 4, 12, 44, 89, 90, 9, 98, 47, 20, 31, 27, 1, 56, 28, 99, 23, 0, 79, 74, 26, 92, 86, 35, 98, 92, 12, 100, 52, 80]
[39, 31, 47, 36, 24, 99, 11, 78, 41, 94, 64, 70, 31, 23, 93, 32, 11, 9, 35, 74, 5, 80, 89, 48, 43, 47, 77, 69, 9, 2, 92, 89, 99, 19, 66, 12, 16, 65, 36, 1, 49, 37, 49, 35, 97, 5, 3, 12, 35]
[68, 99, 25, 100, 36, 63

In [39]:
#a second way to assign subsqeuent rows
import numpy as np
data = np.genfromtxt('large_random_matrix.csv', delimiter=',')
print(data)
d= dict()
for i in range(1,data.shape[1]):
    d[data[0,i-1]] = data[i]
print(d)





[[19. 55. 17. ... 77. 95. 77.]
 [ 0.  5. 23. ... 77. 25. 94.]
 [38. 55. 69. ... 96. 43. 69.]
 ...
 [65. 52. 94. ... 14. 24. 88.]
 [46. 26.  5. ... 32. 71. 80.]
 [72. 28. 93. ... 53. 12. 14.]]
{19.0: array([ 38.,  80.,  71.,  92.,  79.,  25.,  30.,  76.,  27.,  99.,  30.,
        96.,  33.,  61.,  43.,  35.,  43.,  25.,  56.,  80.,  51.,  73.,
        44.,  39.,  26.,  68.,  90.,  41.,  66.,  39.,  57.,  66.,  71.,
        88.,  32.,  43.,  87.,  47.,  49.,  48.,  47.,  68.,  47.,  40.,
        31.,  95.,  42.,  15., 100.,   4.]), 55.0: array([  8.,  97.,  94., 100.,  99.,  78.,  64.,  33.,  92.,  98.,  47.,
        25.,  96.,  19.,  54.,  99.,  23.,   9.,  67.,  39.,   9.,  48.,
        88.,   6.,  98.,  64.,  23.,  37.,  48.,  30.,  15.,  11.,  60.,
        27.,  30.,  32.,   7.,  21.,  65.,  46.,  21.,  36.,  86.,  72.,
        85.,  20.,  81.,  92.,  50.,   7.]), 17.0: array([ 57.,  17.,  68.,  58.,  41.,  27.,  64.,  27.,  39.,  95.,  21.,
        84.,  53.,  22.,  58.,  13.,  71.,

In [44]:
# to group similar elements into a matrix
data = np.genfromtxt('large_random_matrix.csv', delimiter = ',')
groups = {}

for i in range (data.shape[0]):
  for j in range(data.shape[1]):
    element = data[i,j]
    if element not in groups:
      groups[element] = []
    groups[element].append((i,j))

print(groups)

# Create a new matrix to represent group identifiers
group_id_matrix = np.zeros_like(data)

# Assign a unique group identifier for each unique element
group_id = 1
for element, positions in groups.items():
    for pos in positions:
        group_id_matrix[pos] = group_id
    group_id += 1

print("Matrix with group identifiers:")
print(group_id_matrix)


{19.0: [(0, 0), (0, 34), (1, 13), (1, 28), (3, 26), (5, 11), (5, 34), (8, 48), (9, 13), (15, 23), (17, 7), (17, 42), (18, 33), (24, 8), (25, 45), (26, 25), (29, 35), (30, 40), (31, 17), (31, 28), (38, 2), (39, 45), (40, 9), (43, 7), (47, 35), (48, 4), (49, 16)], 55.0: [(0, 1), (0, 8), (2, 1), (3, 32), (5, 20), (5, 27), (10, 14), (15, 45), (16, 10), (19, 43), (22, 27), (23, 3), (23, 39), (27, 9), (28, 47), (32, 22), (32, 44), (36, 14), (39, 29), (39, 44), (43, 0), (43, 18), (48, 42)], 17.0: [(0, 2), (3, 1), (15, 9), (17, 29), (19, 26), (20, 40), (21, 14), (26, 4), (26, 31), (27, 22), (27, 32), (28, 28), (30, 18), (36, 39), (37, 22), (39, 28), (40, 8), (40, 38), (40, 45)], 63.0: [(0, 3), (3, 23), (5, 35), (8, 10), (11, 6), (12, 38), (13, 0), (13, 19), (17, 12), (17, 39), (20, 37), (22, 17), (26, 45), (31, 14), (31, 18), (32, 36), (33, 42), (38, 37), (40, 18), (41, 16), (42, 18), (44, 28), (45, 10), (46, 3), (46, 26), (47, 32), (47, 42), (49, 37)], 41.0: [(0, 4), (1, 29), (2, 43), (3, 4),

In [46]:
#add and subtract matrices
data1 = np.random.randint(0,101,size = (50,50))
data2 = np.random.randint(0,101,size = (50,50))
print(data1)
print(data2)

addition_result = np.add(data1,data2)
print(addition_result)

subtraction_result = np.subtract(data1,data2)
print(subtraction_result)


[[ 3 31  5 ... 35 91 66]
 [54 72 70 ... 70  7 84]
 [12 68 38 ... 58 27 32]
 ...
 [48 81  0 ... 63 65 10]
 [87 25 55 ... 96 76 60]
 [ 9 34 86 ... 28 50 60]]
[[89 47 96 ... 30 51 54]
 [35 44 35 ... 42 35 13]
 [88 28 36 ... 16 85 89]
 ...
 [98  1 53 ... 29 38  8]
 [19 97 58 ... 79  5 51]
 [90 46 45 ... 64 48 25]]
[[ 92  78 101 ...  65 142 120]
 [ 89 116 105 ... 112  42  97]
 [100  96  74 ...  74 112 121]
 ...
 [146  82  53 ...  92 103  18]
 [106 122 113 ... 175  81 111]
 [ 99  80 131 ...  92  98  85]]
[[-86 -16 -91 ...   5  40  12]
 [ 19  28  35 ...  28 -28  71]
 [-76  40   2 ...  42 -58 -57]
 ...
 [-50  80 -53 ...  34  27   2]
 [ 68 -72  -3 ...  17  71   9]
 [-81 -12  41 ... -36   2  35]]


In [47]:
#create an n*n square matrix with sub matrices havinf even sum of opposite corners
n=5
matrix = np.zeros((n,n), dtype= int)
for i in range(n):
  for j in range(n):
    matrix[i,j] = 2*np.random.randint(0,101)
    #consider the fact that the sum of any two even numbers will always be even
print(matrix)

[[132 130  34  16 174]
 [ 90 160  62 138 170]
 [ 32  18 124 154  24]
 [ 82 188  34 100   8]
 [ 36  98 144  68 198]]


In [49]:
#row wise element addition in tuple matrix
tuple_matrix = [(1,2,3),(4,5,6),(7,8,9)]
row_wise_sum = [sum(row) for row in tuple_matrix]
print(tuple_matrix)
print(row_wise_sum)


[(1, 2, 3), (4, 5, 6), (7, 8, 9)]
[6, 15, 24]
